### ISSUE TITLE
PADD version file not found

### ISSUE THREAD

**Issue by ramlev** [jpmck/PADD#39]
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
When trying to start PADD.sh, i'm  getting a lot of errors.

**To Reproduce**
1. start padd.sh

**Expected behavior**
Wanted to see correct info

**Screenshots**
<img width="840" alt="screenshot 2019-01-18 at 14 58 27" src="https://user-images.githubusercontent.com/74152/51391135-8d54c080-1b31-11e9-9c53-6317cc6004cf.png">

**Additional context**
just installed my rpi with pihole.

**Comment by tgjohnst** [comment]
Hi ramlev,

The version file won't be found until PADD has run successfully, but is not the root of the problem. It looks like this is a locale issue - the printf errors are because of your locale's NUMERIC settings, and other errors because you don't have en.us.UTF-8 installed as a locale for your shell. Here's the solution that should fix it:
https://github.com/jpmck/PADD/issues/26#issuecomment-413909951

**Comment by jpmck** [comment]
The en.us.UTF-8 locale is no longer required for PADD (see 17a158b2f85de28d7d11c98997839e7d4285d78e).

This should be resolved.

(Thanks for looking into this @tgjohnst!)
